"""add Note, Tag

Revision ID: b995c2d60b4d
Revises: 3bd25b84b1b3
Create Date: 2025-01-06 16:12:02.446561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b995c2d60b4d'
down_revision: Union[str, None] = '3bd25b84b1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
