"""add Note, Tag

Revision ID: 644e81405d36
Revises: 207891aee8e7
Create Date: 2025-01-06 12:40:30.027018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644e81405d36'
down_revision: Union[str, None] = '207891aee8e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Note', sa.Column('content', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Note', 'content')
    # ### end Alembic commands ###
