"""add Note, Tag

Revision ID: e4f834f9ca67
Revises: 644e81405d36
Create Date: 2025-01-06 13:21:55.835127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e4f834f9ca67'
down_revision: Union[str, None] = '644e81405d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Note', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.drop_index('ix_Note_uesr_id', table_name='Note')
    op.create_index(op.f('ix_Note_user_id'), 'Note', ['user_id'], unique=False)
    op.drop_column('Note', 'uesr_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Note', sa.Column('uesr_id', mysql.VARCHAR(length=36), nullable=False))
    op.drop_index(op.f('ix_Note_user_id'), table_name='Note')
    op.create_index('ix_Note_uesr_id', 'Note', ['uesr_id'], unique=False)
    op.drop_column('Note', 'user_id')
    # ### end Alembic commands ###
